name: Build Version Request
description: Request a specific version build of the software
title: "[Build]: Request for version "
labels: ["build"]
body:
  - type: markdown
    attributes:
      value: |
        Please specify the version you want to build. Leave empty for the default latest version.
  - type: input
    id: build-version
    attributes:
      label: Build Version
      description: Enter the version you want to build. Default is 'latest'.
      placeholder: latest
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        By submitting this request, you agree to comply with the project guidelines.
