name: Build

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour at the start of the hour (UTC)
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  issues:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Using the latest version

      # Step to download the BuildTools.jar file
      - name: Download BuildTools.jar
        run: curl -o BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

      - uses: actions/setup-java@v4  # Using the latest version
        with:
          java-version: 21
          distribution: 'temurin'  # Specifying the Java distribution

      - name: Determine Version
        id: determine_version
        run: |
          if [ "${{ github.event_name }}" == "issues" ]; then
            # Get the issue body and extract the build-version using jq
            ISSUE_BODY=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}" \
              | jq -r '.body')

            # Extract the build-version field from the issue body
            VERSION=$(echo "$ISSUE_BODY" | grep -oP '(?<=Build Version: )[^ \n]*' || echo "latest")
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          else
            echo "VERSION=latest" >> $GITHUB_ENV
          fi

      - name: Output Build Version
        run: |
          echo "Building version: $VERSION"
        env:
          VERSION: ${{ env.VERSION }}

      - name: Run with Java
        run: java -jar BuildTools.jar --rev $VERSION
        env:
          VERSION: ${{ env.VERSION }}

      - name: List files in workspace
        run: ls -alh  # Debugging step to verify generated files

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4  # Using the latest version
        with:
          name: Spigot Artifacts
          path: ./spigot-*.jar

      - name: Auto release
        uses: marvinpinto/action-automatic-releases@latest  # Using the latest version
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: false
          files: |
            spigot-*.jar

  close-issue:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'issues' }}
    steps:
      - name: Close Issue
        uses: peter-evans/close-issue@v3  # Using the latest version
        with:
          issue-number: ${{ github.event.issue.number }}
