name: Build

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight (00:00 UTC)
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  issues:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Step to download the BuildTools.jar file
      - name: Download BuildTools.jar
        run: curl -o BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

      - uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Determine Version
        id: determine_version
        run: |
          # Extract version from issue body
          VERSION=$(echo "${{ github.event.issue.body }}" | grep -oP '(?<=id: build-version\n- \n  value: )\S+')
          if [ -z "$VERSION" ]; then
            echo "VERSION=latest" >> $GITHUB_ENV
          else
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          fi

      - name: Run with Java
        run: java -jar BuildTools.jar --rev ${{ env.VERSION }}

      # Save output as artifact to pass to next jobs
      - name: Save Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: ./*.jar

  upload-artifacts:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      
      # Download build artifacts from previous job
      - name: Download Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Spigot Artifacts
          path: ./*.jar

  upload-release:
    runs-on: ubuntu-latest
    needs: build
    if: "!contains(github.event.issue.body, 'Do not create a release for this build')"
    steps:
      - uses: actions/checkout@v2

      # Download build artifacts from previous job
      - name: Download Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'v1.0.${{ github.run_number }}'
          release_name: 'Release v1.0.${{ github.run_number }}'
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./*.jar
          asset_name: 'BuildTools-v1.0-${{ github.run_number }}.jar'
          asset_content_type: application/java-archive
