name: Build

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight (00:00 UTC)
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  issues:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Step to download the BuildTools.jar file
      - name: Download BuildTools.jar
        run: curl -o BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

      - uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Determine Version
        id: determine_version
        run: |
          if [ "${{ github.event_name }}" == "issues" ]; then
            VERSION=$(echo "${{ github.event.issue.body }}" | grep -oP '(?<=id: build-version\n\s{2}value: )\S+' || echo "")
            if [ -z "$VERSION" ]; then
              echo "VERSION=latest" >> $GITHUB_ENV
            else
              echo "VERSION=$VERSION" >> $GITHUB_ENV
            fi
          else
            echo "VERSION=latest" >> $GITHUB_ENV
          fi

      - name: Run with Java
        run: java -jar BuildTools.jar --rev ${{ env.VERSION }}

      - name: List files in workspace
        run: ls -alh  # Debugging step to verify generated files

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Spigot Artifacts
          path: ./spigot-*.jar

  upload-release:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name != 'issues' }}
    steps:
      - uses: actions/checkout@v2

      - name: Download Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: Spigot Artifacts

      - name: List downloaded files
        run: ls -alh  # Verify the downloaded artifacts

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use default token
        with:
          tag_name: 'latest'  # Use 'latest' as tag name
          release_name: 'latest'  # Use 'latest' as release name
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use default token
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./spigot-*.jar  # Ensure correct file path
          asset_name: 'spigot-${{ env.VERSION }}.jar'  # Use version in asset name
          asset_content_type: application/java-archive

  close-issue:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'issues' }}
    steps:
      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
