name: Build

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour at the start of the hour (UTC)
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  issues:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Using the latest version

      # Step to download the BuildTools.jar file
      - name: Download BuildTools.jar
        run: curl -o BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

      - uses: actions/setup-java@v4  # Using the latest version
        with:
          java-version: 21
          distribution: 'temurin'  # Specifying the Java distribution

      # Conditionally parse issue form inputs
      - name: Issue Forms Body Parser
        id: parse-issue
        if: ${{ github.event_name == 'issues' }}
        uses: zentered/issue-forms-body-parser@v1.5.1

      # Organize Inputs and Determine Version
      - name: Organize Inputs
        id: organize_inputs
        run: |
          if [ "${{ github.event_name }}" == "issues" ]; then
            echo ${{ toJSON(steps.parse-issue.outputs.data) }} | jq '
            def test_input($input; $default):
            if ($input == "*No response*" or $input == "None") then $default else ($input | tostring | gsub("\\\\";""))  end;
            {
              "build_version": test_input(.["build-version"].text; "latest")
            }' > inputs.json
            echo "BUILD_VERSION=$(jq -r '.build_version' inputs.json)" >> $GITHUB_ENV
          else
            echo "BUILD_VERSION=latest" >> $GITHUB_ENV
          fi

      - name: Output Build Version
        run: |
          echo "Building version: $BUILD_VERSION"
        env:
          BUILD_VERSION: ${{ env.BUILD_VERSION }}

      - name: Run with Java
        run: java -jar BuildTools.jar --rev $BUILD_VERSION
        env:
          BUILD_VERSION: ${{ env.BUILD_VERSION }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4  # Using the latest version
        with:
          name: Spigot Artifacts
          path: ./spigot-*.jar

      - name: Auto release
        uses: marvinpinto/action-automatic-releases@latest  # Using the latest version
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: false
          files: |
            spigot-*.jar

  close-issue:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'issues' }}
    steps:
      - name: Close Issue
        uses: peter-evans/close-issue@v3  # Using the latest version
        with:
          issue-number: ${{ github.event.issue.number }}
        continue-on-error: true  # Continue even if this step fails
