name: Build

on:
  schedule:
    - cron: '0 0 * * *'  # This sets the action to run daily at midnight (00:00 UTC)
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Run with Java
        run: java -jar BuildTools.jar --rev latest
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Spigot Artifacts
          path: ./*.jar
