name: Build

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour at the start of the hour (UTC)
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  issues:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Using the latest version

      # Step to download the BuildTools.jar file
      - name: Download BuildTools.jar
        run: curl -o BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

      - uses: actions/setup-java@v4  # Using the latest version
        with:
          java-version: 21
          distribution: 'temurin'  # Specifying the Java distribution

      - name: Determine Version
        id: determine_version
        run: |
          if [ "${{ github.event_name }}" == "issues" ]; then
            VERSION=$(echo "${{ github.event.issue.body }}" | grep -oP '(?<=id: build-version\n\s{2}value: )\S+' || echo "")
            if [ -z "$VERSION" ]; then
              echo "VERSION=latest" >> $GITHUB_ENV
            else
              echo "VERSION=$VERSION" >> $GITHUB_ENV
            fi
          else
            echo "VERSION=latest" >> $GITHUB_ENV
          fi

      - name: Output Build Version
        run: |
          printf "Building version: %s\n" "$VERSION"  # Outputs the build version to the logs
        env:
          VERSION: ${{ env.VERSION }}

      - name: Run with Java
        run: java -jar BuildTools.jar --rev $VERSION  # Correctly using the VERSION environment variable
        env:
          VERSION: ${{ env.VERSION }}

      - name: List files in workspace
        run: ls -alh  # Debugging step to verify generated files

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4  # Using the latest version
        with:
          name: Spigot Artifacts
          path: ./spigot-*.jar

      - name: Auto release
        uses: marvinpinto/action-automatic-releases@latest  # Using the specific version
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: false
          files: |
            spigot-*.jar

  close-issue:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'issues' }}
    steps:
      - name: Close Issue
        uses: peter-evans/close-issue@v3  # Using the specific version
        with:
          issue-number: ${{ github.event.issue.number }}
